language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt


before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  # - python3 manage.py createsuperuser
  - python3 manage.py runserver 0:8000 &
script:
  # - pycodestyle *.py
  # - coverage run --branch *
  # - coverage report --fail-under=95
  - python3 test_*.py