language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  # - pycodestyle *.py
  # - coverage run --branch *
  # - coverage report --fail-under=95
  - python3 gastos/test/test_forms.py