# Generated by Django 3.2 on 2021-05-27 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(1000), django.core.validators.RegexValidator(message='Ingrese un capítulo válido', regex='[1-9][0]{3,3}')], verbose_name='Clave')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(1000), django.core.validators.RegexValidator(message='Ingrese una partida válida', regex='[0-9]{4,4}')], verbose_name='Clave')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=1200, validators=[django.core.validators.MaxLengthValidator(1200)], verbose_name='Descripcion')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.capitulo', verbose_name='Capitulo')),
            ],
        ),
    ]
