# Generated by Django 3.1.3 on 2020-11-20 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=256, verbose_name='Descripcion')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.capitulo', verbose_name='Capitulo')),
            ],
        ),
    ]
