# Generated by Django 3.2 on 2021-05-27 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=2, verbose_name='Programa')),
                ('componente', models.CharField(max_length=2, verbose_name='Componente')),
                ('actividad', models.CharField(max_length=2, verbose_name='Actividad')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(9999999.99), django.core.validators.MinValueValidator(0, 'El monto no puede ser menor a 0')], verbose_name='Monto')),
                ('descripcion', models.CharField(max_length=2300, verbose_name='Descripción')),
                ('mes', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Ingrese un mes válido', regex='^([1-9]|1[012])$')], verbose_name='Mes')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('anio', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Ingrese un año válido', regex='[0-9]{4,4}')], verbose_name='Año')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actividad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad1', to='presupuestos.actividad', verbose_name='Actividad Remitente')),
                ('actividad2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad2', to='presupuestos.actividad', verbose_name='Actividad Destino')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='anio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.presupuesto', verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.partida', verbose_name='Partida'),
        ),
    ]
