# Generated by Django 3.2 on 2021-05-26 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0005_auto_20201206_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoRevolvente',
            fields=[
                ('anio', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Año')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoRevolvente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('pe', 'Pendiente'), ('pa', 'Pagado'), ('ns', 'No solicitado')], default='ns', max_length=2, verbose_name='estatus')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_revolvente.fondorevolvente')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gasto')),
            ],
        ),
    ]
