# Generated by Django 3.1.3 on 2020-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='factura',
            field=models.FileField(blank=True, null=True,
                                   upload_to='cargas/',
                                   verbose_name='Factura'),
        ),
    ]
