# Generated by Django 3.1.3 on 2020-12-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_gasto_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='factura',
            field=models.FileField(
                blank=True, max_length=254, null=True,
                upload_to='gastos', verbose_name='Factura'),
        ),
    ]
