# Generated by Django 3.1.3 on 2020-12-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_auto_20201204_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='factura',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='facturas', verbose_name='Factura'),
        ),
    ]
