# Generated by Django 3.1.3 on 2020-12-06 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_auto_20201204_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(
                100000), django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='precio_total',
            field=models.FloatField(editable=False, validators=[django.core.validators.MaxValueValidator(
                1000000), django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
